package com.proxy.controllers;

public enum LedgerRequestType {
    OBTAIN_COINS, TRANSFER_MONEY, CURRENT_AMOUNT, GLOBAL_LEDGER, CLIENT_LEDGER, REGISTER_KEY, GET_NONCE, VERIFY_OP,  COMMIT_TRANSACTION, COMMIT_WALLET
}
