version: '3'

services:
    replica:
        container_name: replica-${REPLICA_ID}
        build:
            context: ../replica
            dockerfile: Dockerfile
        networks:
            bftsmart-net:
                ipv4_address: 172.28.20.${REPLICA_ID}
                
    redis:
        image: redis
        bftsmart-net:
                ipv4_address: 172.28.100.${REPLICA_ID}
        ports:
            - "6379:6379"

networks:
    bftsmart-net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
