package com.proxy.controllers;

public enum LedgerRequestType {
    OBTAIN_COINS,
    TRANSFER_MONEY,
    CURRENT_AMOUNT,
    GLOBAL_LEDGER,
    CLIENT_LEDGER,
    REGISTER_KEY,
    GET_NONCE,
    VERIFY,
    COMMIT_TRANSACTION,
    COMMIT_WALLET,
    PICK_NOT_MINED_TRANSACTIONS,
    SEND_MINED_BLOCK,
    COMMIT_BLOCK,
    OBTAIN_LAST_BLOCK,
    VALIDATE_SMART_CONTRACT,
    INSTALL_SMART_CONTRACT
}
