package com.clients;

public enum LedgerRequestType {
    OBTAIN_COINS, TRANSFER_MONEY, CURRENT_AMOUNT, GLOBAL_LEDGER, CLIENT_LEDGER, REGISTER_USER, GET_NONCE, VERIFY, COMMIT, PICK_NOT_MINED_TRANSACTIONS, SEND_MINED_BLOCK, COMMIT_BLOCK
}
